{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2007d159",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import json\n",
    "import geopandas as gpd\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import imageio\n",
    "import mapclassify\n",
    "import cv2\n",
    "import os\n",
    "\n",
    "# geopandas - choropleth maps"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9184be68",
   "metadata": {},
   "outputs": [],
   "source": [
    "broj_pozitivnih = []\n",
    "number = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
    "fix_border = ['1,', '2,', '3,', '4,' ,'5,' ,'6,', '7,', '8,', '9,']\n",
    "PATH = 'results/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "66c28dad",
   "metadata": {},
   "outputs": [],
   "source": [
    "def custom_date(date):\n",
    "    return date[8:10]+'.'+date[5:7]+'.'+date[0:4]+'.'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "545dc89b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def rename_geodata(croatia_data):\n",
    "    croatia_data.rename(columns = {'NAME_1' : 'Zupanija'}, inplace=True)\n",
    "    \n",
    "    croatia_data.replace('Bjelovarska-Bilogorska', 'Bjelovarsko-bilogorska', inplace=True)\n",
    "    croatia_data.replace('Brodsko-Posavska', 'Brodsko-posavska', inplace=True)\n",
    "    croatia_data.replace('Dubrovacko-Neretvanska', 'Dubrovačko-neretvanska', inplace=True)\n",
    "    croatia_data.replace('Karlovacka', 'Karlovačka', inplace=True)\n",
    "    croatia_data.replace('Koprivničko-Križevačka', 'Koprivničko-križevačka', inplace=True)\n",
    "    croatia_data.replace('Krapinsko-Zagorska', 'Krapinsko-zagorska', inplace=True)\n",
    "    croatia_data.replace('Licko-Senjska', 'Ličko-senjska', inplace=True)\n",
    "    croatia_data.replace('Medimurska', 'Međimurska', inplace=True)\n",
    "    croatia_data.replace('Osjecko-Baranjska', 'Osječko-baranjska', inplace=True)\n",
    "    croatia_data.replace('Požeško-Slavonska', 'Požeško-slavonska', inplace=True)\n",
    "    croatia_data.replace('Primorsko-Goranska', 'Primorsko-goranska', inplace=True)\n",
    "    croatia_data.replace('Sisacko-Moslavacka', 'Sisačko-moslavačka', inplace=True)\n",
    "    croatia_data.replace('Splitsko-Dalmatinska', 'Splitsko-dalmatinska', inplace=True)\n",
    "    croatia_data.replace('Viroviticko-Podravska', 'Virovitičko-podravska', inplace=True)\n",
    "    croatia_data.replace('Vukovarsko-Srijemska', 'Vukovarsko-srijemska', inplace=True)\n",
    "    croatia_data.replace('Šibensko-Kninska', 'Šibensko-kninska', inplace=True)\n",
    "    croatia_data.replace('Zagrebacka', 'Zagrebačka', inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ffd8c63e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def convert_to_df(df):\n",
    "    df = pd.DataFrame(df, columns = ['Zupanija', 'broj_zarazenih', 'broj_umrlih', 'broj_aktivni', 'pozitivni'])\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "280a378b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def prepare_covidPositive_data(df):\n",
    "    df = df.sort_values(by=['Datum'], ignore_index = True) # ignore_index = resulting axis will be labeled 0, 1, ..., n-1\n",
    "    for i in range(len(df.index)): # po svim zapisima --> len(df.index)\n",
    "        #print(len(df.index))           \n",
    "        for j in range(21): # po zupanijama\n",
    "            if (i == 0): # iznimka prvi dan\n",
    "                df.loc[i][3][j]['pozitivni'] = df.loc[i][3][j]['broj_zarazenih']\n",
    "            elif (df.loc[i][3][j]['broj_zarazenih'] > df.loc[i-1][3][j]['broj_zarazenih']):\n",
    "                df.loc[i][3][j]['pozitivni'] = df.loc[i][3][j]['broj_zarazenih'] - df.loc[i-1][3][j]['broj_zarazenih']\n",
    "            else:\n",
    "                df.loc[i][3][j]['pozitivni'] = 0\n",
    "            broj_pozitivnih.append(df.loc[i][3][j]['pozitivni'])\n",
    "            \n",
    "            # pozitivni = podatak koji sadrži broj novozarazenih tog dana\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "54c90b8e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def fix_legend_border(legend_border):\n",
    "    for i in legend_border:\n",
    "        i.set_text(i.get_text().replace(' ', ''))\n",
    "        if i.get_text()[:2] in fix_border:\n",
    "            tmp = i.get_text()[:2]\n",
    "            i.set_text(i.get_text().replace(tmp, '0,'))\n",
    "        if (i.get_text()[:5] == '-inf,'):\n",
    "            tmp = i.get_text()[:5]\n",
    "            i.set_text(i.get_text().replace(tmp, '0,'))\n",
    "        i.set_text(i.get_text().replace(',', ' - '))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "79d927d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def visualize_covidPositive_data(df, date):\n",
    "    merged_data = croatia_data.merge(df, on = 'Zupanija')\n",
    "    #merged_data.to_file(r'shapefiles/merged_data/combined.shp')\n",
    "    font_title = {'fontname':'sans-serif', 'color':'black', 'size':12, 'weight':'light'}\n",
    "    fig, ax = plt.subplots(1, 1)\n",
    "    ax.axis('off')\n",
    "    merged_data.plot(cmap = 'YlOrBr', edgecolor = 'black', linewidth = 0.18, column = 'pozitivni', ax=ax, \n",
    "                     legend = True, scheme = 'user_defined', vmin = 0,\n",
    "                     classification_kwds = {'bins':[10, 25, 50, 100, 250, 500, 1000, 1250, 1500]},\n",
    "                     legend_kwds = {'loc': 'center left', 'bbox_to_anchor':(1,0.5), 'fmt': '{:.0f}'})\n",
    "    \n",
    "    fix_legend_border(ax.get_legend().texts)\n",
    "        \n",
    "    fig.colorbar  \n",
    "    plt.title(custom_date(date), fontdict = font_title, backgroundcolor = 'floralwhite')\n",
    "    plt.suptitle('Dnevni broj COVID-19 pozitivnih slučajeva' + '\\n po županijama u RH', fontsize=8, \n",
    "                 weight = 'light', backgroundcolor = 'floralwhite', x = 0.25, y = 0.2)\n",
    "    plt.savefig(PATH + date, dpi=70)\n",
    "    plt.close();"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c26fe7f2",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n",
      "/home/lena/.local/lib/python3.8/site-packages/mapclassify/classifiers.py:891: RuntimeWarning: invalid value encountered in double_scalars\n",
      "  gadf = 1 - self.adcm / adam\n"
     ]
    }
   ],
   "source": [
    "croatia_data = gpd.read_file('shapefiles/croatia/HRV_adm1.shp')\n",
    "rename_geodata(croatia_data)\n",
    "\n",
    "f = pd.read_json('data/data_07_10_2021.json')\n",
    "df = prepare_covidPositive_data(pd.DataFrame(f))\n",
    "\n",
    "for i in range(len(df.index)):\n",
    "    for j in df.loc[i]:\n",
    "        per_day_data = convert_to_df(df.loc[i][3])\n",
    "        visualize_covidPositive_data(per_day_data, df.loc[i][2][:-5]) ## yyyy-mm-dd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "a5f15cd8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1415\n",
      "0\n",
      "[False False False ... False False False]\n"
     ]
    }
   ],
   "source": [
    "#print(broj_pozitivnih)\n",
    "print(max(broj_pozitivnih))\n",
    "print(min(broj_pozitivnih))\n",
    "print(np.isnan(broj_pozitivnih))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "bc0b5912",
   "metadata": {},
   "outputs": [],
   "source": [
    "pathdir = './' + PATH\n",
    "images = []\n",
    "for filename in sorted(os.listdir(pathdir)):\n",
    "    if filename.endswith('.png'):\n",
    "        filepath = os.path.join(pathdir, filename)\n",
    "        images.append(imageio.imread(filepath))\n",
    "        images.append(imageio.imread(filepath))\n",
    "imageio.mimsave(pathdir + 'movie.gif', images)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
